groundman_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from super_admin_user.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('su/', include('super_admin_user.urls')),
    # path('gdm/', include('groundman.urls')),
    # path('cur/', include('curator.urls')),
    # path('scr/', include('scorer.urls')),
    path('',login,name="mainlogin" ),
    path('usr_admin/',include('admin_user.urls') ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scorer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('login_auth', views.login_auth, name='login_auth'),  # Root URL
    path('orgdashboard', views.org_dashboard, name='org_dashboard'),  # Root URL
    path('logout', views.logout_view, name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

super_admin_user/urls.py
from django.urls import path
from . import views


urlpatterns = [
path('', views.login, name='login_root'),  # Root URL
path('login_auth', views.login_auth, name='login_auth'),  # Root URL
path('superdashboard', views.dashboard, name='dashboard'),  # Root URL
path('logout', views.logout_root, name='logout_root'),
path('create_admin_user', views.create_admin_user, name='create_admin_user'),
path('admin_users', views.admin_users_list, name='admin_users_list'),
path('admin_users/<int:admin_id>/', views.admin_user_details, name='admin_user_details'),
]

super_admin_user/models.py
from django.db import models
class SuperAdmin(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)
    logo = models.ImageField(upload_to='logos/', blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    mobile = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return self.username

class AdminUserList(models.Model):
    name = models.CharField(max_length=255)
    org_id = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)
    # logo = models.ImageField(upload_to='logos/', blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    mobile = models.CharField(max_length=15, blank=True, null=True)
    superadmin_id= models.ForeignKey(SuperAdmin, on_delete=models.CASCADE, related_name='superadmins')

    def __str__(self):
        return self.username


class MastersList(models.Model):
    org_id = models.CharField(max_length=20, blank=False, null=False)
    tablename = models.CharField(max_length=255,unique=True)
    auth_groundman = models.BooleanField(blank=False)
    auth_curator = models.BooleanField(blank=False)
    auth_scorer = models.BooleanField(blank=False)
    admin_id= models.ForeignKey(AdminUserList, on_delete=models.CASCADE, related_name='adminuserlist')

    def __str__(self):
        return self.org_id+" "+self.tablename

super_admin_user/views.py
from .models import SuperAdmin, AdminUserList
from django.shortcuts import render, redirect
from .templates.super_admin_user.admin.adminForm import AdminUserForm
from django.contrib import messages
from django.db import connection
from .models import MastersList
from admin_user.forms.adminRoleForm import AdminUserRoleForm


def login(request):
    return render(request, 'super_admin_user/login.html')


def login_auth(request):
    try:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            # SuperAdmin.objects.
            try:
                user = SuperAdmin.objects.get( username=username, password=password)
                if user is not None:
                    print(user.name)
                    
                    return render(request, 'super_admin_user/dashboard.html',{'user':user})
                else:
                    messages.error(request, 'Invalid username or password')
                    return render(request, 'super_admin_user/login.html')
            except Exception as e:
                print(e)
                return render(request, 'super_admin_user/login.html')
    except Exception as e:
         print(e)


def dashboard(request):
    return render(request, 'super_admin_user/dashboard.html')


def logout_root(request):
    return redirect('login_root')

# views.py

def createTable(tableName,t,org):
    try:
     with connection.cursor() as cursor:
        if(t=="state"):
            sql=f'''SET FOREIGN_KEY_CHECKS=0;
            CREATE TABLE IF NOT EXISTS {tableName} (
        id INT AUTO_INCREMENT PRIMARY KEY,
        state VARCHAR(255) NOT NULL UNIQUE,
        state_code VARCHAR(2) NOT NULL UNIQUE,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        );SET FOREIGN_KEY_CHECKS=1;
        '''
            cursor.execute(sql)
        elif (t == "city"):
            sql = f'''SET FOREIGN_KEY_CHECKS=0;
            CREATE TABLE IF NOT EXISTS {tableName} (
                id INT AUTO_INCREMENT PRIMARY KEY,
                city_name VARCHAR(255) NOT NULL UNIQUE,
                state_id INT,
                FOREIGN KEY (state_id) REFERENCES {org}_state_master(id),
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
            );SET FOREIGN_KEY_CHECKS=1;
            '''
            cursor.execute(sql)

        elif (t == "ground"):
            sql = f'''SET FOREIGN_KEY_CHECKS=0;
            CREATE TABLE IF NOT EXISTS {tableName} (
            id INT AUTO_INCREMENT PRIMARY KEY,
            org_id VARCHAR(255),
            google_location TEXT,
            year_of_construction VARCHAR(255),
            phone_numbers VARCHAR(255),
            slop_ratio VARCHAR(255),
            ground_name VARCHAR(255),
            state_code VARCHAR(2),
            state_name VARCHAR(255),
            city_name VARCHAR(255),
            count_main_pitches INT,
            count_practice_pitches INT,
            is_side_screen BOOLEAN,
            count_placement_side_screen INT,
            is_broadcasting_facility BOOLEAN,
            is_irrigation_pitches BOOLEAN,
            count_hydrants INT,
            count_pumps INT,
            count_showers INT,
            is_lawn_nursary BOOLEAN,
            name_centre_square VARCHAR(255),
            is_curator_room BOOLEAN,
            is_seperate_practice_area BOOLEAN,
            outfield VARCHAR(255),
            profile_of_outfield VARCHAR(255),
            lawn_species VARCHAR(255),
            is_drainage_system_available BOOLEAN,
            is_water_drainage_system BOOLEAN,
            is_irrigation_system_available BOOLEAN,
            is_availability_of_water BOOLEAN,
            water_source text,
            storage_capacity_in_litres INT,
            count_pop_ups INT,
            size_of_pumps VARCHAR(255),
            is_automation_if_any BOOLEAN,
            is_ground_equipments BOOLEAN,
            is_maintenance_contract BOOLEAN,
            is_maintenance_agency BOOLEAN,
            boundary_size_mtrs text,
            is_availability_of_mot BOOLEAN,
            is_machine_shed BOOLEAN,
            is_soil_shed BOOLEAN,
            is_pitch_or_run_up_covers BOOLEAN,
            size_of_covers_in_mtrs VARCHAR(255),
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        );SET FOREIGN_KEY_CHECKS=1;
            '''
            cursor.execute(sql)
        elif (t == "pitch"):
            sql = f'''SET FOREIGN_KEY_CHECKS=0;
            CREATE TABLE IF NOT EXISTS {tableName} (
            id INT AUTO_INCREMENT PRIMARY KEY,
            org_id VARCHAR(255),
            ground_id INT,
            size_pitch_square text,
            pitch_no VARCHAR(255),
            pitch_type VARCHAR(255),
            profile_of_pitches VARCHAR(255),
            last_used_date DATE,
            last_used_match VARCHAR(255),
            soil_type VARCHAR(255),
            is_uniformtiy_of_grass BOOLEAN,
            size_of_grass text,
            mowing_last_date DATE,
            size_pitch VARCHAR(45),
            pitch_placement VARCHAR(45),
            pitch_in_out VARCHAR(45),
            mowing_size text,
            start_date_of_pitch_preparation DATE,
            date_pitch_construction DATE,
            pitch_details text,
            FOREIGN KEY (ground_id) REFERENCES {org}_ground_master(id),
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        );SET FOREIGN_KEY_CHECKS=1;
            '''
            cursor.execute(sql)
            
        elif (t == "curator_daily_recording"):
            cursor.execute(f'''SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS {tableName} (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pitch_id INT,
    pitch_location VARCHAR(100),
    rolling_start_date VARCHAR(50),
    min_temp VARCHAR(45),
    max_temp VARCHAR(45),
    forecast TEXT,
    clagg_hammer TEXT,
    moisture TEXT,

    machinery_id VARCHAR(100),
    no_of_passes VARCHAR(50),
    rolling_speed VARCHAR(50),
    last_watering_on VARCHAR(50),
    quantity_of_water VARCHAR(50),
    time_of_application VARCHAR(20),
    time_roller VARCHAR(20),
   

    mover_machinery_id VARCHAR(100),
    date_mowing_done_last VARCHAR(50),
    time_of_application_mover VARCHAR(20),
    mowing_done_at_mm VARCHAR(50),

    is_fertilizers_used VARCHAR(20),
    fertilizers_details TEXT,
    chemical_details_remark LONGTEXT,
    remark_by_groundsman TEXT,

    out_machinery_id VARCHAR(100),
    out_no_of_passes VARCHAR(50),
    out_rolling_speed VARCHAR(50),
    out_last_watering_on VARCHAR(50),
    out_quantity_of_water VARCHAR(50),
    out_time_of_application VARCHAR(20),
    out_time_roller VARCHAR(20),

    out_mover_machinery_id VARCHAR(100),
    out_date_mowing_done_last VARCHAR(50),
    time_of_application_out_mover VARCHAR(20),
    out_mowing_done_at_mm VARCHAR(50),
    out_is_fertilizers_used VARCHAR(20),
    out_fertilizers_details TEXT,
    out_chemical_details_remark LONGTEXT,
    out_remark_by_groundsman TEXT,

    practice_machinery_id VARCHAR(100),
    practice_no_of_passes VARCHAR(50),
    practice_rolling_speed VARCHAR(50),
    practice_last_watering_on VARCHAR(50),
    practice_quantity_of_water VARCHAR(50),
    practice_time_of_application VARCHAR(20),
    practice_time_roller VARCHAR(20),

    practice_mover_machinery_id VARCHAR(100),
    practice_date_mowing_done_last VARCHAR(50),
    time_of_application_practice_mover VARCHAR(20),
    practice_mowing_done_at_mm VARCHAR(50),
    practice_is_fertilizers_used VARCHAR(20),
    practice_fertilizers_details TEXT,
    practice_chemical_details_remark LONGTEXT,
    practice_remark_by_groundsman TEXT,

    time_of_application_chemical VARCHAR(20),
    out_time_of_application_chemical VARCHAR(20),
    practice_time_of_application_chemical VARCHAR(20),

    recording_type VARCHAR(45),
    ground_id INT,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    pitch_main VARCHAR(20),
    pitch_practice VARCHAR(20),
    outfield VARCHAR(20),
    practice_area VARCHAR(20),
    
    pitch_main_chemical_weight VARCHAR(20),
    pitch_practice_chemical_weight VARCHAR(20),
    outfield_chemical_weight VARCHAR(20),
    practice_area_chemical_weight VARCHAR(20),
    
    pitch_main_chemical_unit VARCHAR(20),
    pitch_practice_chemical_unit VARCHAR(20),
    outfield_chemical_unit VARCHAR(20),
    practice_area_chemical_unit VARCHAR(20),
    

    FOREIGN KEY (pitch_id) REFERENCES {org}_pitch_master(id),
    FOREIGN KEY (ground_id) REFERENCES {org}_ground_master(id),
    INDEX (pitch_id),
    INDEX (ground_id)
);

SET FOREIGN_KEY_CHECKS=1;
''')
            
            # sql = 
            # print(sql)
            # try:
            #     cursor.execute(sql)
            #     print("huaaaa")
            # except Exception as e:
            #     print(e)
        elif (t == "machinery"):
            sql = f'''SET FOREIGN_KEY_CHECKS=0;
        CREATE TABLE IF NOT EXISTS {tableName} (    
      `id` int NOT NULL AUTO_INCREMENT,
      `equipment_name` varchar(255) NULL,
      `type` varchar(255) NULL,
      `specification` text NULL,
      `unit` varchar(50) NULL,
      `value` text NULL,
      `model` varchar(45) NULL,
      `print_details` varchar(255) NULL,
      PRIMARY KEY (`id`)
            );SET FOREIGN_KEY_CHECKS=1;'''
            cursor.execute(sql)
        elif (t == "match_scores"):
            sql = f'''SET FOREIGN_KEY_CHECKS=0;
            CREATE TABLE IF NOT EXISTS {tableName} (    
            id INT PRIMARY KEY AUTO_INCREMENT,
            match_id INT,

super_admin_user/templates/super_admin_user/admin/admin_user_details.html
<!-- templates/admin_user_detail.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Admin User Detail</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <style>
        .card {
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .card-body {
            padding: 20px;
        }
        .card-title {
            margin-bottom: 10px;
        }
        .table {
            margin-bottom: 20px;
        }
        .table th, .table td {
            vertical-align: middle;
        }
        .img-fluid {
            border-radius: 10px;
            margin: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        {% load static %}
        {% include "super_admin_user/menu.html" %}
        
        <div class="row">
            <div class="col-md-6 offset-md-3">

                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Admin User Information</h5>
                                                <!-- <img src="{{ admin.logo.url }}" alt="Admin Logo" class="img-fluid" style="max-width: 100px;"> Adjust the size as needed -->

                        <table class="table table-bordered">
                            <tr>
                                <th>Username:</th>
                                <td>{{ admin.username }}</td>
                            </tr>
                            <tr>
                                <th>ORG-ID:</th>
                                <td>{{ admin.org_id }}</td>
                            </tr>
                            <tr>
                                <th>Name:</th>
                                <td>{{ admin.name }}</td>
                            </tr>
                            <tr>
                                <th>Email:</th>
                                <td>{{ admin.email }}</td>
                            </tr>
                            <tr>
                                <th>Mobile:</th>
                                <td>{{ admin.mobile }}</td>
                            </tr>
                            <tr>
                                <th>Address:</th>
                                <td>{{ admin.address }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

  <script>
changeMenuTitle("Admin Details")
  </script>
</body>
</html>

super_admin_user/templates/super_admin_user/admin/admin_users_list.html
<!-- templates/admin_user_list.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Admin User List</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style>
        tr
        {
            font-size:70%;
        }
        .title
        {
            font-size:110%;
            background-color:#6cb4ed;
            padding:5px 20px;
            color:white;
            margin-bottom:10px;
        }
    </style>
</head>
<body>
{% include "super_admin_user/menu.html" %}
<!--    <div class="title">Admin User List</div>-->
    <table class="table table-bordered table-sm">
        <thead>
            <tr>
                <th>OrgID</th>
                <th>Username</th>
                <th>Name</th>
                <th>Email</th>
                <th>Mobile</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody class="fs-2">
            {% for admin in admin_users %}
                <tr>
                    <td>{{ admin.org_id }}</td>
                    <td>{{ admin.username }}</td>
                    <td>{{ admin.name }}</td>
                    <td>{{ admin.email }}</td>
                    <td>{{ admin.mobile }}</td>
                    <td>
                        <a href="{% url 'admin_user_details' admin.id %}">View</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script>
changeMenuTitle("Admins List")
  </script>
</body>
</html>

super_admin_user/templates/super_admin_user/admin/create_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Admin User</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
 {% include "super_admin_user/menu.html" %}
    <div class="container mt-1">

        <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Create</button>
        </form>

        {% if messages %}
            <div class="mt-3">
                <ul class="list-group">
                    {% for message in messages %}
                        <li class="list-group-item">{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>

    <!-- Include Bootstrap JS and dependencies (Optional for additional functionality) -->


 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


<script>


                document.querySelector("#id_superadmin_id").selectedIndex=1

changeMenuTitle("Create Admin")

</script>


<script>
    $(document).ready(function{

        $("form").submit(function(event){
            event.preventDefault()

            if(new RegExp(/^[a-z_]$/).test($("#id_org_id").val()))
        {
            $(this).submit()


        }
        else{
            alert("wrong")
        }
        })
    })
</script>
</body>
</html>