admin_user/urls.py
from django.urls import path
from . import views


urlpatterns = [
path('', views.login, name='login'),  # Root URL
path('login', views.login, name='login_org'),  # Root URL
path('groundform', views.groundform, name='groundform'),  # Root URL
path('curator/login', views.curatorLogin, name='login_curator'),  # Root URL
path('groundman/login', views.groundmanLogin, name='login_groundman'),  # Root URL
path('scorer/login', views.scorerLogin, name='login_scorer'),  # Root URL
path('login_auth', views.login_auth, name='login_auth'),  # Root URL
path('login_auth_role', views.login_auth_role, name='login_auth_role'),  # Root URL
path('create_admin_user_role', views.create_admin_user_role, name='create_admin_user_role'),
path('admin_users_roles_list', views.admin_user_roles_list, name='admin_user_roles_list'),
path('admin_user_role_details/<int:admin_id>', views.admin_user_role_details, name='admin_user_role_details'),
path('orgdashboard', views.org_dashboard, name='org_dashboard'),  # Root URL
path('roledashboard', views.role_dashboard, name='role_dashboard'),  # Root URL
path('logout', views.logout_view, name='logout'),
path('add_state_city', views.add_state_city, name='add_state_city'),
path('list_state_city', views.list_state_city, name='list_state_city'),
path('create_ground_master/', views.create_ground_master, name='create_ground_master'),
path('update_ground_master/<int:ground_id>', views.update_ground_master, name='update_ground_master'),
path('delete_ground_master/<int:ground_id>', views.delete_ground_master, name='delete_ground_master'),
path('update_pitches/<int:ground_id>/', views.update_pitches, name='update_pitches'),
path('ground_list/', views.ground_list, name='ground_list'),
path('get_ground/<str:ground_id>', views.get_ground, name='get_ground'),
path('ground_pitches/<int:ground_id>', views.ground_pitches, name='ground_pitches'),
path('edit_pitch/<int:pitch_id>/<int:ground_id>', views.edit_pitch, name='edit_pitch'),
path('add_pitch/', views.addNewPItch, name='add_pitch'),
path('save_edit_pitch', views.save_edit_pitch, name='save_edit_pitch'),
path('get_cities/', views.get_cities, name='get_cities'),
path('curator_daily_recording_form/', views.curator_daily_recording_form, name='curator_daily_recording_form'),
path('update_daily/<int:daily_id>', views.update_daily, name='update_daily'),
path('delete_daily/<int:daily_id>', views.delete_daily, name='delete_daily'),
path('curator_daily_recording_list/', views.curator_daily_recording_list, name='curator_daily_recording_list'),
path('get_pitches/<str:ground_id>', views.get_pitches, name='get_pitches'),
path('get_pitch/<str:pitch_id>', views.get_pitch, name='get_pitch'),
path('get_all_pitches/', views.get_all_pitches, name='get_all_pitches'),
path('get_grounds/', views.get_grounds, name='get_grounds'),
path('machinery/', views.machinery_list, name='machinery_list'),
    path('machinery/insert/', views.insert_machinery, name='insert_machinery'),
    path('machinery/update/<str:machinery_id>', views.update_machinery, name='update_machinery'),
    path('machinery/delete/<str:machinery_id>', views.delete_machinery, name='delete_machinery'),
    path('machinery/<int:machinery_id>/', views.get_machinery_details, name='get_machinery_details'),
path('matches/', views.match_list, name='match_list'),        # URL to list all matches
    path('matches/insert/', views.insert_match, name='insert_match'),  # URL to insert a new match
    path('matches/update/<int:match_id>/', views.update_match, name='update_match'),  # URL to update a match
    path('matches/delete/<int:match_id>/', views.delete_match, name='delete_match'),  # URL to update a match
    path('add_score/<int:match_id>/', views.add_score, name='add_score'),
    path('save_scores/', views.save_scores, name='save_scores'),
    path('get_match_scores/<int:match_id>/', views.get_match_scores, name='get_match_scores'),
    path('match_scores_list/<int:match_id>', views.match_scores_list, name='match_scores_list'),
    path('delete_score/<int:score_id>/', views.delete_score, name='delete_score'),
    path('update_score/<int:score_id>/', views.update_score, name='update_score'),
path('api/machinery-data/', views.get_machinery_data, name='machinery_data'),
 path('getAllChemicals/', views.fertilizer_list, name='fertilizer_list'),
    path('addChemical/', views.fertilizer_add, name='fertilizer_add'),
    path('editChemical/<int:id>/', views.fertilizer_edit, name='fertilizer_edit'),
    path('deleteChemical/<int:id>/', views.fertilizer_delete, name='fertilizer_delete'),
    path('get-fertilizers-json/', views.get_fertilizers_json, name='get_fertilizers_json'),
    path('get_chemical/<int:fert_id>/', views.get_single_fertilizer, name='get_single_fertilizer'),
    #####################reports
    
    path('report-match/',views.reportMatch, name='report_match'),
    path('chemicalsReport/',views.chemicalsReport, name='chemicalsReport'),
    path('fetchChemicalsReport/',views.fertilizer_usage_report, name='fertilizer_usage_report'),
    path("machinery-report/", views.machinery_report, name="machinery_report"),
    path("machinery_pass_report/", views.machinery_pass_report, name="machinery_pass_report"),

    path('fetch-tournaments/', views.fetch_tournaments, name='fetch_tournaments'),
    path('fetch-cities/', views.fetch_cities, name='fetch_cities'),
    path('fetch-grounds/', views.fetch_grounds, name='fetch_grounds'),
    path('fetch-matches/', views.fetch_matches, name='fetch_matches'),

    # path('generate_report/', views.generate_report, name='generate_report')
    path('match-records/', views.fetch_match_records, name='match_records'),
    path('match-records/download-csv/', views.download_csv, name='download_csv'),
    path('match-records/download-pdf/', views.download_pdf, name='download_pdf'),
    path('match-records/daily_download_csv/', views.daily_download_csv, name='daily_download_csv'),
    path('match-records/match_download_csv/', views.match_download_csv, name='match_download_csv'),
    # path('match-records/daily_download_pdf/', views.daily_download_pdf, name='daily_download_pdf'),
    path('curator-daily-records/', views.curator_recording_report, name='curator_daily_records'),
    path('match-report/', views.match_report, name='match_daily_records'),
    
]

groundman_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from super_admin_user.views import login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('su/', include('super_admin_user.urls')),
    # path('gdm/', include('groundman.urls')),
    # path('cur/', include('curator.urls')),
    # path('scr/', include('scorer.urls')),
    path('',login,name="mainlogin" ),
    path('usr_admin/',include('admin_user.urls') ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scorer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('login_auth', views.login_auth, name='login_auth'),  # Root URL
    path('orgdashboard', views.org_dashboard, name='org_dashboard'),  # Root URL
    path('logout', views.logout_view, name='logout'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin_user/models.py
from django.db import models

class AdminRole(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)
    profileImage = models.ImageField(upload_to='profiles/', null=False)
    org_id = models.CharField(max_length=255, null=False)
    ground_id = models.CharField(max_length=255, null=False)
    role = models.CharField(max_length=255, null=False)
    mobile = models.CharField(max_length=255, null=False)
    date_reg = models.DateField(null=False)

    def __str__(self):
        return "Username:"+self.username+" Organization ID:"+self.org_id

admin_user/forms/GroundMasterForm.py
from django import forms
from django.db import connection

class GroundMasterForm(forms.Form):
    org_id = forms.CharField(max_length=255)
    ground_name = forms.CharField(max_length=255)
    state_name = forms.ChoiceField(choices=[], required=True)
    state_code = forms.CharField(widget=forms.HiddenInput(), required=False)
    city_name = forms.ChoiceField(choices=[], required=False)
    count_main_pitches = forms.IntegerField()
    count_practice_pitches = forms.IntegerField()
    is_side_screen = forms.BooleanField(required=False)
    count_placement_side_screen = forms.IntegerField(required=False)
    is_broadcasting_facility = forms.BooleanField(required=False)
    is_irrigation_pitches = forms.BooleanField(required=False)
    count_hydrants = forms.IntegerField(required=False)
    count_pumps = forms.IntegerField(required=False)
    count_showers = forms.IntegerField(required=False)
    is_lawn_nursary = forms.BooleanField(required=False)
    name_centre_square = forms.CharField(max_length=255, required=False)
    is_curator_room = forms.BooleanField(required=False)
    is_seperate_practice_area = forms.BooleanField(required=False)
    outfield = forms.CharField(max_length=255, required=False)
    profile_of_outfield = forms.CharField(max_length=255, required=False)
    lawn_species = forms.CharField(max_length=255, required=False)
    is_drainage_system_available = forms.BooleanField(required=False)
    is_water_drainage_system = forms.BooleanField(required=False)
    is_irrigation_system_available = forms.BooleanField(required=False)
    is_availability_of_water = forms.BooleanField(required=False)
    is_water_source = forms.BooleanField(required=False)
    storage_capacity_in_litres = forms.IntegerField(required=False)
    count_pop_ups = forms.IntegerField(required=False)
    size_of_pumps = forms.CharField(max_length=255, required=False)
    is_automation_if_any = forms.BooleanField(required=False)
    is_ground_equipments = forms.BooleanField(required=False)
    is_maintenance_contract = forms.BooleanField(required=False)
    is_maintenance_agency = forms.BooleanField(required=False)
    boundary_size_mtrs = forms.IntegerField(required=False)
    is_availability_of_mot = forms.BooleanField(required=False)
    is_machine_shed = forms.BooleanField(required=False)
    is_soil_shed = forms.BooleanField(required=False)
    is_pitch_or_run_up_covers = forms.BooleanField(required=False)
    size_of_covers_in_mtrs = forms.CharField(max_length=255, required=False)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(GroundMasterForm, self).__init__(*args, **kwargs)
        self.fields['state_name'].choices = [('','Select any state')] + self.get_states()
        if self.request.method == 'POST':
            self.fields['city_name'].choices = self.get_cities(self.request.POST.get('state_name'))

    def get_states(self):
        org_id = self.request.session.get('org_id')
        with connection.cursor() as cursor:
            cursor.execute(f'SELECT id, state, state_code FROM {org_id}_state_master')
            states = cursor.fetchall()
        return [(state[0], state[1]) for state in states]

    def get_cities(self, state_id):
        org_id = self.request.session.get('org_id')
        with connection.cursor() as cursor:
            cursor.execute(f'SELECT id, city_name FROM {org_id}_city_master WHERE state_id = %s', [state_id])
            cities = cursor.fetchall()
        return [(city[0], city[1]) for city in cities]

admin_user/forms/PitchMasterForm.py
from django import forms

class PitchMasterForm(forms.Form):
    def __init__(self, *args, **kwargs):
        pitches = kwargs.pop('pitches')
        super(PitchMasterForm, self).__init__(*args, **kwargs)
        for pitch in pitches:
            pitch_id = pitch[0]
            self.fields[f'pitch_no_{pitch_id}'] = forms.CharField(initial=pitch[3], required=True)
            self.fields[f'pitch_type_{pitch_id}'] = forms.CharField(initial=pitch[4], required=False)
            self.fields[f'profile_of_pitches_{pitch_id}'] = forms.CharField(initial=pitch[5], required=False)
            self.fields[f'last_used_date_{pitch_id}'] = forms.DateField(initial=pitch[6], required=False)
            self.fields[f'last_used_match_{pitch_id}'] = forms.CharField(initial=pitch[7], required=False)
            self.fields[f'is_uniformtiy_of_grass_{pitch_id}'] = forms.BooleanField(initial=pitch[8], required=False)
            self.fields[f'size_of_grass_{pitch_id}'] = forms.CharField(initial=pitch[9], required=False)
            self.fields[f'mowing_last_date_{pitch_id}'] = forms.DateField(initial=pitch[10], required=False)
            self.fields[f'mowing_size_{pitch_id}'] = forms.CharField(initial=pitch[11], required=False)
            self.fields[f'start_date_of_pitch_preparation_{pitch_id}'] = forms.DateField(initial=pitch[12], required=False)
            self.fields[f'soil_type_{pitch_id}'] = forms.CharField(initial=pitch[13], required=False)

admin_user/forms/StateCityForm.py
from django import forms
from django.db import connection

class StateCityForm(forms.Form):
    state = forms.CharField(max_length=255)
    state_code = forms.CharField(max_length=2)
    city_name = forms.CharField(max_length=255)
    state_id = forms.ChoiceField(choices=[], required=False)

    def __init__(self, request, *args, **kwargs):
        super(StateCityForm, self).__init__(*args, **kwargs)
        self.request = request
        self.fields['state_id'].choices = self.get_states()

    def get_states(self):
        org_id = self.request.session.get('org_id')
        with connection.cursor() as cursor:
            cursor.execute(f'SELECT id, state FROM {org_id}_state_master')
            states = cursor.fetchall()
        return [(state[0], state[1]) for state in states]

admin_user/forms/adminRoleForm.py
from datetime import date
from django import forms
from admin_user.models import AdminRole

class AdminUserRoleForm(forms.ModelForm):
    role = forms.ChoiceField(
        choices=[("Groundman", "Groundman"), ("Curator", "Curator"), ("Scorer", "Scorer")],
        required=True,
        widget=forms.Select(attrs={'class': 'form-select'})  # Use form-select for Bootstrap 5 dropdowns
    )

    class Meta:
        model = AdminRole
        fields = ['org_id','ground_id', 'name', 'email', 'password', 'username', 'profileImage', 'role', 'mobile', 'date_reg']
        widgets = {
            'org_id': forms.TextInput(attrs={'class': 'form-control', 'readonly': 'readonly'}),
            'ground_id': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Select Ground'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Name'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter Email-id'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter Password'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Username'}),
            'profileImage': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Mobile No.'}),
            'date_reg': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(AdminUserRoleForm, self).__init__(*args, **kwargs)
        self.fields['date_reg'].initial = date.today()

admin_user/templates/admin_user/admin_users_roles_list.html
<!-- templates/admin_user_list.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Admin User List</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <style>
        .card {
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        .card-body {
            padding: 20px;
        }
        .card-title {
            margin-bottom: 10px;
        }
        .table {
            margin-bottom: 20px;
        }
        .table th, .table td {
            vertical-align: middle;
        }
    </style>
</head>
<body>
    <div class="container">
        {% include "admin_user/menu.html" %}
        <div class="row">
            <div class="col-md-12">
<!--                <h2>Admin User List</h2>-->
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Admin User List</h5>
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Username</th>
                                    <th>Org ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th>Role</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for admin in admin_roles %}
                                    <tr>
                                        <td>{{ admin.username }}</td>
                                        <td>{{ admin.org_id }}</td>
                                        <td>{{ admin.name }}</td>
                                        <td>{{ admin.email }}</td>
                                        <td>{{ admin.mobile }}</td>
                                        <td>{{ admin.role }}</td>
                                        <td>
                                            <a href="{% url 'admin_user_role_details' admin.id %}">View</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
   changeMenuTitle("Admin User List")
</script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

admin_user/templates/admin_user/create_admin_role.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Admin Role</title>
    <!-- Include Bootstrap 5 CSS and Font Awesome -->
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
{% include "admin_user/menu.html" %}
    <div class="container mt-5">
<!--        <h2 class="mb-4">Create Admin Role</h2>-->
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
              <!-- Messages Section -->
        {% if messages %}
            <div class="mt-3 alert alert-info">
                <ul class="list-group">
                    {% for message in messages %}
                        <li class="list-group-item">{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
            <!-- Organization ID (Readonly) -->
            <div class="mb-3">
                <label for="id_org_id" class="form-label">Organization ID</label>
                {{ form.org_id }}
            </div>
            <div class="mb-3">
                <label for="id_ground_id" class="form-label">Ground</label>
                {{ form.ground_id }}
            </div>
            <!-- Name -->
            <div class="mb-3">
                <label for="id_name" class="form-label">Name</label>
                {{ form.name }}
            </div>
            <!-- Email -->
            <div class="mb-3">
                <label for="id_email" class="form-label">Email</label>
                {{ form.email }}
            </div>
            <!-- Password -->
            <div class="mb-3">
                <label for="id_password" class="form-label">Password</label>
                {{ form.password }}
            </div>
            <!-- Username -->
            <div class="mb-3">
                <label for="id_username" class="form-label">Username</label>
                {{ form.username }}
            </div>
            <!-- Profile Image -->
            <div class="mb-3">
                <label for="id_profileImage" class="form-label">Profile Image</label>
                {{ form.profileImage }}
            </div>
            <!-- Role -->
            <div class="mb-3">
                <label for="id_role" class="form-label">Role</label>
                {{ form.role }}
            </div>
            <!-- Mobile -->
            <div class="mb-3">
                <label for="id_mobile" class="form-label">Mobile</label>
                {{ form.mobile }}
            </div>
            <!-- Date Registration -->
            <div class="mb-3">
                <label for="id_date_reg" class="form-label">Date of Registration</label>
                {{ form.date_reg }}
            </div>
            <!-- Submit Button -->
            <button type="submit" class="btn btn-primary">
                <i class="fas fa-user-plus"></i> Create
            </button>
        </form>


    </div>

    <!-- Include Bootstrap JS and dependencies -->
<!--    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>-->
<script>
$(document).ready(function(){

    axios.get("/usr_admin/get_grounds").then((result) => {
                $("#id_ground_id").html("")
                $("#id_ground_id").append(`<option value=''>Select Ground</option>`)
              

                result.data.grounds.forEach(function (g) {
                    $("#id_ground_id").append(`<option value='${g.ground[0]}'>${g.ground[6]}</option>`)
                })

            }).catch((error) => {
                console.log(error)

            })
})
</script>

</body>
</html>

admin_user/templates/admin_user/ground_pitches.html
<!DOCTYPE html>
<html>

<head>
  <title>Ground List</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

</head>

<body>
  {% include "admin_user/menu.html" %}
  {% for ground in grounds %}
  <div class="row">
    <div class="col-lg-4 col-sm-12">
      <h1><span>Ground :</span> <span>{{ ground.6 }}</span></h1>
    </div>
    <div class="col-lg-8 col-sm-12 d-flex align-items-center">
      <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modalAddPitch">Add New Pitch</button>
    </div>
  </div>

  <div class="modal fade" id="modalAddPitch" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Pitch</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <input type="hidden" name="ground_id" id="ground_id" value="{{ground.0}}">
          <div class="mb-3">
            <label for="formFile" class="form-label">Pitch Type</label>
            <select class="form-select" id="pitch_type" aria-label="Default select example">
              <option selected value="">Open pitch type</option>
              <option value="main">Main</option>
              <option value="practice">Practice</option>
            </select>
          </div>


        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" id="btnaddpitch">Add</button>
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  <table class="table table-bordered text-center">
    <caption class="caption-top text-center text-white bg-success py-2">Main/Center Pitches</caption>
    <tr>
      
      <th>Pitch Type</th>
      <th>Pitch No</th>
      <th>Ground Id</th>
      <th>Actions</th>
    </tr>




    {% for pitch in pitches %}
    {% if pitch.5 == "main" %}
    <tr style="text-align:center">
     
      <td class="text-capitalize"> {{ pitch.5 }}</td>
      <td>{{ pitch.4 }}</td>
      <td> {{ pitch.2 }}</td>
      <td> <a href="/usr_admin/edit_pitch/{{ pitch.0 }}/{{pitch.2}}">Edit</a></td>
    </tr>
    {% endif %}
    {% endfor %}


  </table>
  <table class="table table-bordered text-center mt-3">
    <caption class="caption-top text-center text-white bg-primary py-2">Practice Pitches</caption>
    <tr>
    
      <th>Pitch Type</th>
      <th>Pitch No</th>
      <th>Ground Id</th>
      <th>Actions</th>
    </tr>




    {% for pitch in pitches %}
    {% if pitch.5 == "practice" %}
    <tr style="text-align:center">
     
      <td class="text-capitalize"> {{ pitch.5 }}</td>
      <td>{{ pitch.4 }}</td>
      <td> {{ pitch.2 }}</td>
      <td> <a href="/usr_admin/edit_pitch/{{ pitch.0 }}/{{pitch.2}}">Edit</a></td>
    </tr>
    {% endif %}
    {% endfor %}


  </table>
</body>
<script>
  $(document).ready(function () {
    $("#btnaddpitch").click(function () {
      const pitch_type = $("#pitch_type").val();
      if (pitch_type) {
        $.ajax({
          url: '{% url "add_pitch" %}',
          method: "post",
          data: { "pitch_type":pitch_type,"ground_id":$("#ground_id").val().trim()},
                 success: function (data) {
            console.log("success")
          }
        });
      }
      else {
        alert("save failed..")
      }
    })

  })
</script>

</html>